version: '3.8'

services:
  pdftool-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PDFTOOL_DEBUG=false
      - PDFTOOL_LOG_LEVEL=INFO
      - PDFTOOL_API_HOST=0.0.0.0
      - PDFTOOL_API_PORT=8000
      - PDFTOOL_MAX_FILE_SIZE=104857600  # 100MB
    volumes:
      - ./temp:/app/temp
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
    depends_on:
      - pdftool-api
    restart: unless-stopped
    profiles:
      - production

volumes:
  temp_data:
  log_data: